server:
  port: 8080

spring:
  application:
    name: API-GATEWAY
  cloud:
    gateway:
      routes:
        - id: customer-service
          uri: lb://CUSTOMER-SERVICE
          predicates:
            - Path=/customer/**
          filters:
            - name: CircuitBreaker
              args:
                name: customerServiceCircuitBreaker
                fallbackUri: forward:/customerFallback

        - id: company-service
          uri: lb://COMPANY-SERVICE
          predicates:
            - Path=/company/**
          filters:
            - name: CircuitBreaker
              args:
                name: companyServiceCircuitBreaker
                fallbackUri: forward:/companyFallback

        - id: transaction-service
          uri: lb://TRANSACTION-SERVICE
          predicates:
            - Path=/transaction/**
          filters:
            - name: CircuitBreaker
              args:
                name: transactionServiceCircuitBreaker
                fallbackUri: forward:/transactionFallback

        - id: sale-service
          uri: lb://SALE-SERVICE
          predicates:
            - Path=/sale/**
          filters:
            - name: CircuitBreaker
              args:
                name: saleServiceCircuitBreaker
                fallbackUri: forward:/saleFallback

        - id: listing-service
          uri: lb://LISTING-SERVICE
          predicates:
            - Path=/listing/**
          filters:
            - name: CircuitBreaker
              args:
                name: listingServiceCircuitBreaker
                fallbackUri: forward:/listingFallback

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost

resilience4j:
  circuitbreaker:
    instances:
      customerServiceCircuitBreaker:
        register-health-indicator: true
        ring-buffer-size-in-closed-state: 10
        ring-buffer-size-in-half-open-state: 5
        wait-duration-in-open-state: 60s
        failure-rate-threshold: 50
      companyServiceCircuitBreaker:
        register-health-indicator: true
        ring-buffer-size-in-closed-state: 10
        ring-buffer-size-in-half-open-state: 5
        wait-duration-in-open-state: 60s
        failure-rate-threshold: 50
      transactionServiceCircuitBreaker:
        register-health-indicator: true
        ring-buffer-size-in-closed-state: 10
        ring-buffer-size-in-half-open-state: 5
        wait-duration-in-open-state: 60s
        failure-rate-threshold: 50
      saleServiceCircuitBreaker:
        register-health-indicator: true
        ring-buffer-size-in-closed-state: 10
        ring-buffer-size-in-half-open-state: 5
        wait-duration-in-open-state: 60s
        failure-rate-threshold: 50
      listingServiceCircuitBreaker:
        register-health-indicator: true
        ring-buffer-size-in-closed-state: 10
        ring-buffer-size-in-half-open-state: 5
        wait-duration-in-open-state: 60s
        failure-rate-threshold: 50
